project:
  type: website
  output-dir: docs

website:
  title: "  Altı Üstü Data's Project Lab"
  navbar:
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: Data
        href: data.qmd
      - text: Analysis
        href: analysis.qmd

            
    tools:
      - icon: github
        href: https://twitter.com

  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "Hacettepe IE - EMU 430 - Fall 2023" 
    border: true
format:
 html:
    mainfont : arial
    fontcolor: "#FFFCFC"
    linkcolor: "#F49F9F"
    toc: true
    toc-location: left
    theme: 
      light: darkly
      dark: darkly
    css: styles.css


editor: visual

