---
title: "Analysis"
---

Our dataset consists of 3 columns. Provinces, pm10_values and forest area. Provinces are categorical variables representing the geographical location or provinces in Turkey, pm10_values are quantitative variables representing the average PM10 values, a common measure of air quality, higher values indicate higher levels of air pollution and forest_area values are quantitative variables representing the percentage of forest area per square kilometer. It reflects the extent of forest coverage in each province. The distribution of PM10 values across provinces can be visualized using a histogram. This would provide insights into the range and frequency of air pollution levels. The distribution of forest area percentages can be visualized using a histogram as well. This helps understand the variation in forest coverage among provinces. Correlation between PM10 values and forest area can be visually represented with a scatter plot. We can ompare provinces in different regions of Turkey to identify regional patterns in air pollution and forest area. A bar chart or grouped box plot can be useful for such comparisons.We can Rank provinces based on PM10 values and forest area to identify provinces with the highest and lowest values. This can be visualized using bar charts or a dual-axis plot.

Here is some additional analysis for our project ( we'll be use provinces further in our analysis):

```{r}
# Libraries
library(ggplot2)
library(dplyr)
library(gridExtra)

# Read data from CSV file
data1 <- "https://raw.githubusercontent.com/emu-hacettepe-analytics/emu430-fall2023-team-alti_ustu_data/master/project_data.csv"

project_data <- read.csv(data1)

# Data Summary
summary_data <- project_data %>% summarise(
    Avg_PM10 = mean(pm10_values),
    SD_PM10 = sd(pm10_values),
    Avg_Forest_Area = mean(forest_area),
    SD_Forest_Area = sd(forest_area)
  )

# Histogram of PM10 Values
p1 <- ggplot(project_data, aes(x = pm10_values)) +
  geom_histogram(binwidth = 5, fill = "blue", color = "black") +
  theme_minimal() +
  labs(title = "Histogram of PM10 Values",
       x = "PM10 Values", y = "Frequency")

# Histogram of Forest Area
p2 <- ggplot(project_data, aes(x = forest_area)) +
  geom_histogram(binwidth = 5, fill = "green", color = "black") +
  theme_minimal() +
  labs(title = "Histogram of Forest Area",
       x = "Forest Area", y = "Frequency")

# Scatter Plot with Regression Line
p3 <- ggplot(project_data, aes(x = pm10_values, y = forest_area)) +
  geom_point(color = "red") +
  labs(title = "Scatter Plot of PM10 Values Compared to Forest Area",
       x = "PM10 Values", y = "Forest Area")

# Display the plots
grid.arrange(p1, p2, p3, ncol = 1)

data1 <- "https://raw.githubusercontent.com/emu-hacettepe-analytics/emu430-fall2023-team-alti_ustu_data/master/project_data.csv"

summary_data

```
